version: "1.0"
services:
  code:
    image: lscr.io/linuxserver/code-server:4.16.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - PASSWORD= #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD= #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - code-data:/config
    ports:
      - 8443:8443
    restart: always
  init:
    image: klakegg/hugo:0.111.3
    entrypoint: [""]
    command: >
      sh -c "sleep 30 &&
             cd ./workspace &&
             hugo new site site &&
             cd ./site &&
             hugo new theme placeholder &&
             cd .. &&
             chmod -R 777 site"
    volumes:
      - code-data:/src
    depends_on:
      - code
  server:
    image: klakegg/hugo:0.111.3
    entrypoint: [""]
    command: >
      sh -c "sleep 60 &&
             cd ./workspace/site &&
             hugo server -p 1313 --disableFastRender"
    volumes:
      - code-data:/src
    ports:
      - 1313:1313
    depends_on:
      - code
    restart: always
volumes:
  code-data:
